[package]
name = "Key-Value-Store-Assignment"
version = "0.1.0"
edition = "2024"

[dependencies]
sysinfo = "0.30"
dashmap = "7.0.0-rc2"
tokio = {version = "1.44.1" , features = ["full"]}
lru = "0.13.0"